### ISSUE TITLE
Top, bottom position

### ISSUE THREAD

**Issue by jquimera** [slavanga/pusha#1]
Very good! How to use in top / bottom position?

PS: Would not it be better to have these options also in Javascript?

'.my-panel {
  @include pusha-panel(
    $direction: left, // left, right, top, bottom
    $mode: push, // push, pull, overlay, fade
    $width: 260px,
    $height: 100%,
    $background: #fff
  );
}'

PS2: What was wrong here? https://codepen.io/johnquimera/pen/RMzZmw

**Comment by slavanga** [comment]
Hey, thank you for trying out Pusha.

Only the two most common use cases (left and right) are provided by default.

If you need other configurations you have to create a new class and use the mixin like this:
```scss
.pusha-panel--top {
  @include pusha-panel(top);
}
```

**Comment by jquimera** [comment]
@slavanga Its plugin is good but could be much better as these options can be easily passed through javascript. Like this: https://github.com/vmitsaras/js-offcanvas#options

**Comment by jquimera** [comment]
@slavanga How to improve this? https://codepen.io/johnquimera/pen/RMzZmw

**Comment by slavanga** [comment]
The modifiers option in js-offcanvas only lets you define which classes are applied to the panel. Additional CSS is still required to make it work.

I prefer letting the developers decide which configurations they really need instead of adding a ton of additional CSS by default.

On the JS side you can improve the initialisation of multiple panels like this:
https://codepen.io/anon/pen/OvKbVM?editors=0010

**Comment by jquimera** [comment]
@slavanga I understand. Everything is fine now. I already got the hang of your plugin. Alias is very light and easy to customize. Congratulations.

Thank you.
